/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dance;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.TransferHandler;

public class DanceFloor extends javax.swing.JFrame {

    ThreadMusic music;
    Boolean musicEnable = true;
    ClassLoader cl = getClass().getClassLoader();
    File musicSelected = new File(cl.getResource("./music/eletronic.wav").getFile());

    /**
     * Creates new form DanceFloor
     */
    public DanceFloor() {
        initComponents();

        char1.setVisible(false);
        char3.setVisible(false);
        char2.setVisible(false);
        char4.setVisible(false);
        char5.setVisible(false);
        char6.setVisible(false);

        music = new ThreadMusic(musicSelected.getName(), musicSelected.getPath());
        music.start();
    }

    private void changeSelectedMusic(String musicPath) {
        this.musicSelected = new File(cl.getResource(musicPath).getFile());

        music.stopAudio();
        music = new ThreadMusic(musicSelected.getName(), musicSelected.getPath());

        if (musicEnable) {
            music.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        char6 = new javax.swing.JLabel();
        char5 = new javax.swing.JLabel();
        char4 = new javax.swing.JLabel();
        char3 = new javax.swing.JLabel();
        char2 = new javax.swing.JLabel();
        char1 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        title_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        options = new javax.swing.JPanel();
        char1_img = new javax.swing.JLabel();
        char2_img = new javax.swing.JLabel();
        char3_img = new javax.swing.JLabel();
        char4_img = new javax.swing.JLabel();
        char5_img = new javax.swing.JLabel();
        char6_img = new javax.swing.JLabel();
        button_play_stop = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        floor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        char6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/spider_man.gif"))); // NOI18N
        jPanel1.add(char6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 150, 150));

        char5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/simpsons.gif"))); // NOI18N
        jPanel1.add(char5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 109, 150));

        char4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        char4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/shrek.gif"))); // NOI18N
        jPanel1.add(char4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 120, 150));

        char3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/duende.gif"))); // NOI18N
        jPanel1.add(char3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 140, 150));

        char2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/charmander.gif"))); // NOI18N
        jPanel1.add(char2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 140, 150));

        char1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/anime.gif"))); // NOI18N
        jPanel1.add(char1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 109, 150));

        menu.setBackground(new java.awt.Color(82, 160, 17));

        title_panel.setBackground(new java.awt.Color(82, 160, 17));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(69, 0, 73));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bailão do SO");

        javax.swing.GroupLayout title_panelLayout = new javax.swing.GroupLayout(title_panel);
        title_panel.setLayout(title_panelLayout);
        title_panelLayout.setHorizontalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        title_panelLayout.setVerticalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        options.setBackground(new java.awt.Color(82, 160, 17));

        char1_img.setBackground(new java.awt.Color(255, 255, 255));
        char1_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/char1.png"))); // NOI18N
        char1_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        char1_img.setOpaque(true);
        char1_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                char1_imgMouseClicked(evt);
            }
        });

        char2_img.setBackground(new java.awt.Color(255, 255, 255));
        char2_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/char2.png"))); // NOI18N
        char2_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        char2_img.setOpaque(true);
        char2_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                char2_imgMouseClicked(evt);
            }
        });

        char3_img.setBackground(new java.awt.Color(255, 255, 255));
        char3_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/char3.png"))); // NOI18N
        char3_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        char3_img.setOpaque(true);
        char3_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                char3_imgMouseClicked(evt);
            }
        });

        char4_img.setBackground(new java.awt.Color(255, 255, 255));
        char4_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/char4.png"))); // NOI18N
        char4_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        char4_img.setOpaque(true);
        char4_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                char4_imgMouseClicked(evt);
            }
        });

        char5_img.setBackground(new java.awt.Color(255, 255, 255));
        char5_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/char5.png"))); // NOI18N
        char5_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        char5_img.setOpaque(true);
        char5_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                char5_imgMouseClicked(evt);
            }
        });

        char6_img.setBackground(new java.awt.Color(255, 255, 255));
        char6_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/char6.png"))); // NOI18N
        char6_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        char6_img.setOpaque(true);
        char6_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                char6_imgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsLayout.createSequentialGroup()
                        .addComponent(char5_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(char6_img, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsLayout.createSequentialGroup()
                        .addComponent(char1_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(char2_img, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsLayout.createSequentialGroup()
                        .addComponent(char3_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(char4_img, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(char1_img, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(char2_img, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(char4_img, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(char3_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(char5_img, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(char6_img, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button_play_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_play_stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stop_music.png"))); // NOI18N
        button_play_stop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_play_stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_play_stopMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Músicas");

        jComboBox1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(69, 0, 73));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padrão", "Eu me remexo muito", "Beyonce", "Gangnam Style" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Personagens");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(options, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(0, 55, Short.MAX_VALUE)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                                .addComponent(button_play_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(title_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_play_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 250, 650));

        floor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/dance_floor.gif"))); // NOI18N
        jPanel1.add(floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void char1_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_char1_imgMouseClicked
        ThreadDance character = new ThreadDance(char1, this, 109, 150);
        character.start();
    }//GEN-LAST:event_char1_imgMouseClicked

    private void char3_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_char3_imgMouseClicked
        ThreadDance character = new ThreadDance(char3, this, 109, 150);
        character.start();
    }//GEN-LAST:event_char3_imgMouseClicked

    private void char4_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_char4_imgMouseClicked
        ThreadDance character = new ThreadDance(char4, this, 217, 173);
        character.start();
    }//GEN-LAST:event_char4_imgMouseClicked

    private void char5_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_char5_imgMouseClicked
        ThreadDance character = new ThreadDance(char5, this, 66, 133);
        character.start();
    }//GEN-LAST:event_char5_imgMouseClicked

    private void char6_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_char6_imgMouseClicked
        ThreadDance character = new ThreadDance(char6, this, 150, 150);
        character.start();
    }//GEN-LAST:event_char6_imgMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() == 0) {
            this.changeSelectedMusic("./music/eletronic.wav");
        } else if (jComboBox1.getSelectedIndex() == 1) {
            this.changeSelectedMusic("./music/remexo_muito.wav");
        } else if (jComboBox1.getSelectedIndex() == 2) {
            this.changeSelectedMusic("./music/beyonce.wav");
        } else if (jComboBox1.getSelectedIndex() == 3) {
            this.changeSelectedMusic("./music/gangnam_style.wav");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void button_play_stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_play_stopMouseClicked
        if (musicEnable) {
            music.stopAudio();
            musicEnable = false;
            ClassLoader cl = getClass().getClassLoader();
            File icon = new File(cl.getResource("./img/play_music.png").getFile());
            button_play_stop.setIcon(new ImageIcon(icon.getPath()));
        } else {
            music = new ThreadMusic(musicSelected.getName(), musicSelected.getPath());
            music.start();
            musicEnable = true;
            ClassLoader cl = getClass().getClassLoader();
            File icon = new File(cl.getResource("./img/stop_music.png").getFile());
            button_play_stop.setIcon(new ImageIcon(icon.getPath()));
        }
    }//GEN-LAST:event_button_play_stopMouseClicked

    private void char2_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_char2_imgMouseClicked
        ThreadDance character = new ThreadDance(char2, this, 150, 150);
        character.start();
    }//GEN-LAST:event_char2_imgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanceFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanceFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanceFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanceFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanceFloor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel button_play_stop;
    private javax.swing.JLabel char1;
    private javax.swing.JLabel char1_img;
    private javax.swing.JLabel char2;
    private javax.swing.JLabel char2_img;
    private javax.swing.JLabel char3;
    private javax.swing.JLabel char3_img;
    private javax.swing.JLabel char4;
    private javax.swing.JLabel char4_img;
    private javax.swing.JLabel char5;
    private javax.swing.JLabel char5_img;
    private javax.swing.JLabel char6;
    private javax.swing.JLabel char6_img;
    private javax.swing.JLabel floor;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel options;
    private javax.swing.JPanel title_panel;
    // End of variables declaration//GEN-END:variables
}
